---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - watcher.openstack.org
  resources:
  - watcherapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watcher.openstack.org
  resources:
  - watcherapis/finalizers
  verbs:
  - update
- apiGroups:
  - watcher.openstack.org
  resources:
  - watcherapis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - watcher.openstack.org
  resources:
  - watcherappliers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watcher.openstack.org
  resources:
  - watcherappliers/finalizers
  verbs:
  - update
- apiGroups:
  - watcher.openstack.org
  resources:
  - watcherappliers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - watcher.openstack.org
  resources:
  - watcherdecisionengines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watcher.openstack.org
  resources:
  - watcherdecisionengines/finalizers
  verbs:
  - update
- apiGroups:
  - watcher.openstack.org
  resources:
  - watcherdecisionengines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - watcher.openstack.org
  resources:
  - watchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watcher.openstack.org
  resources:
  - watchers/finalizers
  verbs:
  - update
- apiGroups:
  - watcher.openstack.org
  resources:
  - watchers/status
  verbs:
  - get
  - patch
  - update
