# permissions for end users to view watcherappliers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: watcherapplier-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: watcher-operator
    app.kubernetes.io/part-of: watcher-operator
    app.kubernetes.io/managed-by: kustomize
  name: watcherapplier-viewer-role
rules:
- apiGroups:
  - watcher.openstack.org
  resources:
  - watcherappliers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - watcher.openstack.org
  resources:
  - watcherappliers/status
  verbs:
  - get
