apiVersion: v1
kind: Secret
metadata:
  name: metric-storage-prometheus-config
  namespace: openstack
stringData:
  host: metric-storage-prometheus.openstack.svc
  port: "9090"
  ca_secret: "combined-ca-bundle"
  ca_key: "internal-ca-bundle.pem"
