apiVersion: watcher.openstack.org/v1beta1
kind: Watcher
metadata:
  name: watcher
spec:
  databaseInstance: "openstack"
  apiServiceTemplate:
    tls:
      caBundleSecretName: "combined-ca-bundle"
  decisionengineServiceTemplate:
    customServiceConfig: |
      [watcher_cluster_data_model_collectors.compute]
      period = 60
      [watcher_cluster_data_model_collectors.storage]
      period = 60
